import React, { useState } from 'react';
import { useAdminEvents } from '../../hooks/admin/useAdminEvents';
import { EventItem } from '../../types';
import { AdminEventCard } from '../../components/admin/events/AdminEventCard';
import { AdminEventForm } from '../../components/admin/events/AdminEventForm';
import { getMonthName } from '../../utils/dateUtils';

interface AdminEventsProps {
    user: any;
    uploadImage: (file: File) => Promise<string | null>;
    triggerToast: (msg: string) => void;
}

const AdminEvents: React.FC<AdminEventsProps> = ({ user, uploadImage, triggerToast }) => {
    const { events, isLoading, saveEventMutation, deleteEventMutation } = useAdminEvents(user);

    const [isCreatingEvent, setIsCreatingEvent] = useState(false);
    const [editingEvent, setEditingEvent] = useState<Partial<EventItem> | null>(null);
    const [isUploading, setIsUploading] = useState(false);

    // Filter & Search State
    const [searchTerm, setSearchTerm] = useState('');
    const [filterCategory, setFilterCategory] = useState('Todos');

    const handleEdit = (event: EventItem) => {
        setEditingEvent(event);
        setIsCreatingEvent(true);
    };

    const handleCloseForm = () => {
        setIsCreatingEvent(false);
        setEditingEvent(null);
    };

    const handleSave = async (data: Partial<EventItem>, file: File | null) => {
        try {
            setIsUploading(true);
            let url = data.imageUrl;

            if (file) {
                const up = await uploadImage(file);
                if (up) url = up;
            }

            await saveEventMutation.mutateAsync({ ...data, image_url: url, id: editingEvent?.id || undefined });
            triggerToast(editingEvent ? "Evento actualizado correctamente" : "Evento creado con éxito");
            handleCloseForm();
        } catch (error) {
            console.error(error);
            triggerToast("Error al guardar evento");
        } finally {
            setIsUploading(false);
        }
    };

    const filteredEvents = events.filter(e => {
        const matchesSearch = e.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
            e.location.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesCategory = filterCategory === 'Todos' || e.category === filterCategory;
        return matchesSearch && matchesCategory;
    });

    const stats = {
        total: events.length,
        featured: events.filter(e => e.isFeatured).length,
        upcomingThisMonth: events.filter(e => {
            if (!e.date) return false;
            const d = new Date(e.date); // dateUtils handles formatting, but here we need date object logic. 
            // Ideally we'd parse properly, but standard string 'YYYY-MM-DD' works in constructor often.
            // Let's rely on string parsing if generated by input type='date'
            const now = new Date();
            // Simple check if it's current month
            // Note: date input gives YYYY-MM-DD which is UTC usually or local, need care. 
            // For simple dashboard stats, generic check is fine.
            try {
                return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
            } catch { return false; }
        }).length
    };

    return (
        <div className="flex flex-col h-full bg-[#F8F9FA] dark:bg-black/95">
            {/* Header Section */}
            <div className="flex-none px-8 pt-10 pb-6 md:px-12">
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-10">
                    <div>
                        <h2 className="text-4xl md:text-5xl font-serif font-bold text-brand-obsidian dark:text-white leading-tight tracking-tight mb-3">
                            Agenda <span className="text-brand-primary">Ministerial</span>
                        </h2>
                        <p className="text-brand-obsidian/40 dark:text-white/40 font-medium text-sm md:text-base max-w-xl leading-relaxed">
                            Organiza y gestiona todos los eventos, cultos y actividades especiales de la iglesia desde un solo lugar.
                        </p>
                    </div>

                    <button
                        onClick={() => { setEditingEvent(null); setIsCreatingEvent(true); }}
                        className="group bg-brand-obsidian dark:bg-brand-primary text-white dark:text-brand-obsidian px-8 py-5 rounded-2xl font-black text-xs uppercase tracking-[0.2em] shadow-2xl hover:scale-[1.02] active:scale-95 transition-all flex items-center gap-3"
                    >
                        <div className="bg-white/10 dark:bg-black/10 rounded-full w-6 h-6 flex items-center justify-center group-hover:rotate-90 transition-transform">
                            <span className="material-symbols-outlined text-sm">add</span>
                        </div>
                        Nuevo Evento
                    </button>
                </div>

                {/* Filters & Search Bar */}
                <div className="flex flex-col xl:flex-row gap-6 mb-8 items-start xl:items-center justify-between">
                    {/* Search */}
                    <div className="relative w-full xl:w-96 group">
                        <span className="absolute left-5 top-1/2 -translate-y-1/2 material-symbols-outlined text-brand-obsidian/20 dark:text-white/20 group-focus-within:text-brand-primary transition-colors">search</span>
                        <input
                            type="text"
                            placeholder="Buscar por título o ubicación..."
                            value={searchTerm}
                            onChange={e => setSearchTerm(e.target.value)}
                            className="w-full bg-white dark:bg-brand-surface pl-14 pr-6 py-4 rounded-2xl border border-brand-obsidian/5 dark:border-white/5 text-sm font-bold focus:ring-2 focus:ring-brand-primary/20 outline-none shadow-sm transition-all"
                        />
                    </div>

                    {/* Category Pills */}
                    <div className="flex gap-2 overflow-x-auto no-scrollbar max-w-full pb-2 xl:pb-0">
                        {['Todos', 'Celebración', 'Célula', 'Taller', 'Misiones', 'Jóvenes'].map(cat => (
                            <button
                                key={cat}
                                onClick={() => setFilterCategory(cat)}
                                className={`px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest whitespace-nowrap transition-all border ${filterCategory === cat
                                    ? 'bg-brand-primary text-brand-obsidian border-brand-primary shadow-lg shadow-brand-primary/20'
                                    : 'bg-white dark:bg-brand-surface text-brand-obsidian/40 dark:text-white/40 border-brand-obsidian/5 dark:border-white/5 hover:bg-gray-50 dark:hover:bg-white/5'
                                    }`}
                            >
                                {cat}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Quick Stats (Optional Compact View) */}
                <div className="grid grid-cols-3 gap-6 mb-2 hidden md:grid">
                    <div className="flex items-center gap-3 opacity-50">
                        <span className="material-symbols-outlined text-brand-obsidian dark:text-white">event</span>
                        <span className="text-xs font-bold uppercase tracking-wider">{stats.total} Eventos Totales</span>
                    </div>
                    <div className="flex items-center gap-3 opacity-50">
                        <span className="material-symbols-outlined text-amber-500">star</span>
                        <span className="text-xs font-bold uppercase tracking-wider">{stats.featured} Destacados</span>
                    </div>
                </div>
            </div>

            {/* Content Grid */}
            <div className="flex-1 overflow-y-auto px-8 md:px-12 pb-32 custom-scrollbar">
                {isLoading ? (
                    <div className="h-64 flex flex-col items-center justify-center opacity-40">
                        <div className="w-12 h-12 border-4 border-brand-primary border-t-transparent rounded-full animate-spin mb-6" />
                        <p className="text-xs font-bold uppercase tracking-widest text-brand-obsidian dark:text-white">Cargando agenda...</p>
                    </div>
                ) : filteredEvents.length === 0 ? (
                    <div className="h-96 flex flex-col items-center justify-center text-center opacity-40 border-2 border-dashed border-brand-obsidian/5 dark:border-white/5 rounded-[3rem]">
                        <div className="w-24 h-24 bg-brand-obsidian/5 dark:bg-white/5 rounded-full flex items-center justify-center mb-6">
                            <span className="material-symbols-outlined text-4xl text-brand-obsidian dark:text-white">event_busy</span>
                        </div>
                        <h3 className="text-xl font-serif font-bold text-brand-obsidian dark:text-white mb-2">Sin eventos encontrados</h3>
                        <p className="text-sm font-medium">Intenta cambiar los filtros o crea un nuevo evento.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-8">
                        {filteredEvents.map(event => (
                            <AdminEventCard
                                key={event.id}
                                event={event}
                                onEdit={handleEdit}
                                onDelete={(id) => deleteEventMutation.mutate(id)}
                            />
                        ))}
                    </div>
                )}
            </div>

            {/* Modal Form */}
            {isCreatingEvent && (
                <AdminEventForm
                    initialData={editingEvent || {}}
                    onClose={handleCloseForm}
                    onSave={handleSave}
                    isSaving={isUploading}
                />
            )}
        </div>
    );
};

export default AdminEvents;
